#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

if (PHP_VERSION_ID < 80000) {
    echo "\e[31mOwi Framework requires PHP 8.0 or higher. You are running " . PHP_VERSION . ".\e[39m\n";
    exit(1);
}

require_once __DIR__ . '/owicore/console/Console.php';

use Owi\console\Console;

(new Console())->run($argv);
